apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification
          image: notification-svc:0.1.0
          env:
            - name: NATS_URL
              value: "nats://nats.nats:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  selector:
    app: notification-svc
  ports:
    - name: http
      port: 80
      targetPort: 3000
