apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-svc
  namespace: monitor
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: order-svc
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-svc
  namespace: monitor
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: payment-svc
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
